### ISSUE TITLE
Project does not build with use_frameworks! in Podfile

### ISSUE THREAD

**Issue by evermeer** [cine-io/cineio-broadcast-ios#6]
In my project I am using various Swif libraries. Because of that I have to add use_frameworks! to my Podfile.
When doing that, I first got the error that VCSimleSession.h could not be found.
I could solve this In CineBroadcasterProtocol.h by changing:
    #import <videocore/api/iOS/VCSimpleSession.h>
In:
    #import <videocore/VCSimpleSession.h>

After that I get an error iostream file not found for the #include <iostream> in VideoCore\AudioMixer.h
This looks related to:
http://stackoverflow.com/questions/29501154/cocoapods-spec-that-uses-c-and-compiles-as-a-framework

**Comment by martint028** [comment]
how to solve it?

**Comment by cprovatas** [comment]
@evermeer How did you solve?
